import { useState, useRef } from "react";
import { Authenticator } from "@aws-amplify/ui-react";
import { uploadData } from "aws-amplify/storage";
import "@aws-amplify/ui-react/styles.css";
import "./App.css";

const API_URL =
  "https://9bd3e5wwxb.execute-api.us-east-1.amazonaws.com/generate";

const S3_BUCKET = "ai-social-media-generator";
const S3_REGION = "us-east-1";

type ApiResponse = {
  success: boolean;
  content?: string;
  hashtags?: string[];
  platform?: string;
  tone?: string;
  hasImage?: boolean;
  bucket?: string;
  key?: string;
  imageContentType?: string;
  model?: string;
  error?: string;
};

function App() {
  const [topic, setTopic] = useState("");
  const [platform, setPlatform] = useState("LinkedIn");
  const [tone, setTone] = useState("Professional");

  // Automatically generated after uploading an image
  const [imageKey, setImageKey] = useState("");
  const [uploadedFileName, setUploadedFileName] = useState("");

  const [content, setContent] = useState("");
  const [hashtags, setHashtags] = useState<string[]>([]);

  const [loading, setLoading] = useState(false);
  const [uploading, setUploading] = useState(false);
  const [uploadProgress, setUploadProgress] = useState(0);

  const [error, setError] = useState("");
  const [copied, setCopied] = useState(false);

  const fileInputRef = useRef<HTMLInputElement>(null);

  /*
   * Upload image directly from browser to
   * the existing S3 bucket through Amplify Storage.
   */
  async function handleImageUpload(
    event: React.ChangeEvent<HTMLInputElement>
  ) {
    const file = event.target.files?.[0];

    if (!file) {
      return;
    }

    setError("");
    setUploadProgress(0);

    // Only images are allowed
    if (!file.type.startsWith("image/")) {
      setError("Please select an image file.");
      event.target.value = "";
      return;
    }

    // 5 MB limit
    const maxSize = 5 * 1024 * 1024;

    if (file.size > maxSize) {
      setError("Image size must be less than 5 MB.");
      event.target.value = "";
      return;
    }

    setUploading(true);

    try {
      /*
       * Create a unique S3 key.
       *
       * Example:
       * public/1723212345678-my-certificate.jpg
       */
      const safeFileName = file.name
        .replace(/[^a-zA-Z0-9._-]/g, "-")
        .replace(/-+/g, "-");

      const path = `public/${Date.now()}-${safeFileName}`;

      const uploadResult = await uploadData({
        path,
        data: file,

        options: {
          bucket: {
            bucketName: S3_BUCKET,
            region: S3_REGION,
          },

          contentType: file.type,

          onProgress: ({ transferredBytes, totalBytes }) => {
            if (totalBytes) {
              const progress = Math.round(
                (transferredBytes / totalBytes) * 100
              );

              setUploadProgress(progress);
            }
          },
        },
      }).result;

      /*
       * Amplify returns the actual S3 path.
       */
      setImageKey(uploadResult.path);
      setUploadedFileName(file.name);
      setUploadProgress(100);

      console.log("Image uploaded successfully.");
      console.log("S3 bucket:", S3_BUCKET);
      console.log("S3 key:", uploadResult.path);
    } catch (err) {
      console.error("Image upload error:", err);

      if (err instanceof Error) {
        setError(`Image upload failed: ${err.message}`);
      } else {
        setError("Image upload failed. Please try again.");
      }

      setImageKey("");
      setUploadedFileName("");
      setUploadProgress(0);
    } finally {
      setUploading(false);

      // Allow selecting the same file again
      event.target.value = "";
    }
  }

  function openFilePicker() {
    fileInputRef.current?.click();
  }

  async function generatePost() {
    setError("");
    setContent("");
    setHashtags([]);
    setCopied(false);

    if (!topic.trim() && !imageKey.trim()) {
      setError("Please enter a topic or upload an image.");
      return;
    }

    setLoading(true);

    try {
      const requestBody: {
        topic?: string;
        platform: string;
        tone: string;
        imageKey?: string;
      } = {
        platform,
        tone,
      };

      if (topic.trim()) {
        requestBody.topic = topic.trim();
      }

      /*
       * This is now automatically generated by the
       * S3 upload. The user does NOT type it.
       */
      if (imageKey.trim()) {
        requestBody.imageKey = imageKey.trim();
      }

      console.log("Sending request to API Gateway:", requestBody);

      const response = await fetch(API_URL, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify(requestBody),
      });

      const data: ApiResponse = await response.json();

      if (!response.ok || !data.success) {
        throw new Error(data.error || "Failed to generate the post.");
      }

      setContent(data.content || "");
      setHashtags(data.hashtags || []);
    } catch (err) {
      console.error("Generate post error:", err);

      if (err instanceof Error) {
        setError(err.message);
      } else {
        setError("Something went wrong. Please try again.");
      }
    } finally {
      setLoading(false);
    }
  }

  async function copyPost() {
    const fullText = `${content}\n\n${hashtags.join(" ")}`;

    try {
      await navigator.clipboard.writeText(fullText);

      setCopied(true);

      setTimeout(() => {
        setCopied(false);
      }, 2000);
    } catch {
      setError("Unable to copy the generated post.");
    }
  }

  function clearAll() {
    setTopic("");
    setImageKey("");
    setUploadedFileName("");
    setUploadProgress(0);
    setContent("");
    setHashtags([]);
    setError("");
    setCopied(false);

    if (fileInputRef.current) {
      fileInputRef.current.value = "";
    }
  }

  return (
    <Authenticator>
      {({ signOut, user }) => (
        <div className="app">
          {/* Header */}
          <header className="header">
            <div className="brand">
              <div className="brand-icon">✦</div>

              <div>
                <h1>AI Social Media Generator</h1>
                <p>Create professional social media content with AI</p>
              </div>
            </div>

            <div className="header-right">
              <div className="status">
                <span className="status-dot"></span>
                AI Powered
              </div>

              <button
                type="button"
                className="signout-button"
                onClick={signOut}
              >
                Sign out
              </button>
            </div>
          </header>

          {/* Main */}
          <main className="container">
            <section className="hero">
              <span className="hero-badge">AWS • Amazon Bedrock</span>

              <h2>
                Turn your ideas into
                <span> engaging posts.</span>
              </h2>

              <p>
                Generate polished social media content using Amazon Nova 2
                Lite.
              </p>
            </section>

            <div className="workspace">
              {/* Generator Card */}
              <section className="card generator-card">
                <div className="card-header">
                  <div>
                    <h3>Create your post</h3>
                    <p>Tell the AI what you want to post about.</p>
                  </div>

                  <div className="sparkle">✦</div>
                </div>

                {/* Topic */}
                <div className="field">
                  <label htmlFor="topic">
                    Topic
                    <span className="optional">
                      Optional if image is provided
                    </span>
                  </label>

                  <textarea
                    id="topic"
                    value={topic}
                    onChange={(e) => setTopic(e.target.value)}
                    placeholder="Example: I completed my Networking Essentials certification..."
                    rows={5}
                  />
                </div>

                {/* Platform */}
                <div className="field">
                  <label htmlFor="platform">Platform</label>

                  <select
                    id="platform"
                    value={platform}
                    onChange={(e) => setPlatform(e.target.value)}
                  >
                    <option value="LinkedIn">LinkedIn</option>
                    <option value="Instagram">Instagram</option>
                    <option value="Facebook">Facebook</option>
                    <option value="X">X / Twitter</option>
                  </select>
                </div>

                {/* Tone */}
                <div className="field">
                  <label htmlFor="tone">Tone</label>

                  <select
                    id="tone"
                    value={tone}
                    onChange={(e) => setTone(e.target.value)}
                  >
                    <option value="Professional">Professional</option>
                    <option value="Friendly">Friendly</option>
                    <option value="Casual">Casual</option>
                    <option value="Inspirational">Inspirational</option>
                    <option value="Confident">Confident</option>
                  </select>
                </div>

                {/* Image Upload */}
                <div className="field">
                  <label>
                    Image
                    <span className="optional">Optional</span>
                  </label>

                  {/* Hidden native file input */}
                  <input
                    ref={fileInputRef}
                    type="file"
                    accept="image/jpeg,image/png,image/webp,image/gif"
                    onChange={handleImageUpload}
                    style={{ display: "none" }}
                  />

                  {!uploadedFileName ? (
                    <button
                      type="button"
                      className="upload-button"
                      onClick={openFilePicker}
                      disabled={uploading || loading}
                    >
                      {uploading ? (
                        <>
                          <span className="spinner"></span>
                          Uploading {uploadProgress}%
                        </>
                      ) : (
                        <>📷 Upload Image</>
                      )}
                    </button>
                  ) : (
                    <div className="uploaded-image-box">
                      <div className="uploaded-image-info">
                        <span className="uploaded-check">✓</span>

                        <div>
                          <strong>{uploadedFileName}</strong>
                          <small>
                            Uploaded successfully to Amazon S3
                          </small>
                        </div>
                      </div>

                      <button
                        type="button"
                        className="remove-image-button"
                        onClick={() => {
                          setImageKey("");
                          setUploadedFileName("");
                          setUploadProgress(0);

                          if (fileInputRef.current) {
                            fileInputRef.current.value = "";
                          }
                        }}
                        disabled={loading}
                      >
                        Remove
                      </button>
                    </div>
                  )}

                  <small>
                    JPG, PNG, WEBP or GIF • Maximum 5 MB
                  </small>

                  {imageKey && (
                    <small className="s3-upload-status">
                      ✓ S3 image ready for AI processing
                    </small>
                  )}
                </div>

                {/* Error */}
                {error && (
                  <div className="error-box">
                    <span>⚠</span>
                    <p>{error}</p>
                  </div>
                )}

                {/* Buttons */}
                <div className="actions">
                  <button
                    className="generate-button"
                    onClick={generatePost}
                    disabled={loading || uploading}
                  >
                    {loading ? (
                      <>
                        <span className="spinner"></span>
                        Generating...
                      </>
                    ) : (
                      <>✦ Generate Post</>
                    )}
                  </button>

                  <button
                    className="clear-button"
                    onClick={clearAll}
                    disabled={loading || uploading}
                  >
                    Clear
                  </button>
                </div>
              </section>

              {/* Result Card */}
              <section className="card result-card">
                <div className="card-header">
                  <div>
                    <h3>Generated content</h3>
                    <p>
                      Your AI-generated social media post will appear here.
                    </p>
                  </div>

                  {content && (
                    <button className="copy-button" onClick={copyPost}>
                      {copied ? "✓ Copied" : "Copy"}
                    </button>
                  )}
                </div>

                {!content && !loading && (
                  <div className="empty-state">
                    <div className="empty-icon">✦</div>

                    <h4>Your post will appear here</h4>

                    <p>
                      Enter a topic, upload an image if needed, choose your
                      platform and tone, then click
                      <strong> Generate Post</strong>.
                    </p>
                  </div>
                )}

                {loading && (
                  <div className="loading-state">
                    <div className="large-spinner"></div>

                    <h4>Creating your post...</h4>

                    <p>
                      Amazon Nova 2 Lite is generating your content.
                    </p>
                  </div>
                )}

                {content && !loading && (
                  <div className="result-content">
                    <div className="post-meta">
                      <span>{platform}</span>
                      <span>{tone}</span>
                      {imageKey && <span>Image included</span>}
                    </div>

                    <div className="post-text">{content}</div>

                    {hashtags.length > 0 && (
                      <div className="hashtags-section">
                        <h4>Hashtags</h4>

                        <div className="hashtags">
                          {hashtags.map((hashtag, index) => (
                            <span
                              key={`${hashtag}-${index}`}
                              className="hashtag"
                            >
                              {hashtag}
                            </span>
                          ))}
                        </div>
                      </div>
                    )}

                    <button
                      className="copy-full-button"
                      onClick={copyPost}
                    >
                      {copied
                        ? "✓ Copied to clipboard"
                        : "📋 Copy Post & Hashtags"}
                    </button>
                  </div>
                )}
              </section>
            </div>

            {/* Architecture */}
            <section className="architecture">
              <p>Powered by</p>

              <div className="architecture-items">
                <span>React</span>
                <span>→</span>
                <span>AWS Amplify</span>
                <span>→</span>
                <span>Amazon S3</span>
                <span>→</span>
                <span>API Gateway</span>
                <span>→</span>
                <span>AWS Lambda</span>
                <span>→</span>
                <span>Amazon Bedrock</span>
              </div>
            </section>
          </main>

          <footer>
            <p>
              AI Social Media Generator • Built with AWS & React
            </p>
          </footer>
        </div>
      )}
    </Authenticator>
  );
}

export default App;
